dist: bionic
sudo: false

language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"

env:
  - CASS_DRIVER_NO_CYTHON=1

addons:
  apt:
    packages:
    - build-essential
    - python-dev
    - pypy-dev
    - libc-ares-dev
    - libev4
    - libev-dev

install:
  - pip install --upgrade setuptools importlib-metadata
  - pip install tox-travis lz4

script:
  - tox
  - tox -e gevent_loop
  - tox -e eventlet_loop
